-- ==============================================================================
-- MPG REPUTATION — LOCAL DATABASE SEED PLACEHOLDER
-- ==============================================================================
-- Notice:
--   Interactive authentication accounts and tenant fixtures are managed
--   deterministically via the official Supabase Auth Admin API script:
--
--     scripts/bootstrap-local-dev.mjs (invoked by `pnpm dev:reset`)
--
--   This file intentionally avoids direct manual maintenance of Supabase Auth
--   internals (auth.users / auth.identities) in accordance with official Supabase
--   engineering guidance.
-- ==============================================================================
